# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.cache/wt [current_project]
set_property parent.project_path /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_output_repo /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.srcs/sources_1/imports/Projects/NexysVideo_A.sv
read_verilog -library xil_defaultlib {
  /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.srcs/sources_1/new/hexconverter.v
  /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.srcs/sources_1/imports/Projects/uart.v
  /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.srcs/sources_1/new/ram_iface.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.srcs/constrs_1/imports/Projects/NexysVideo_Master.xdc
set_property used_in_implementation false [get_files /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.srcs/constrs_1/imports/Projects/NexysVideo_Master.xdc]


synth_design -top NexysVideo_A -part xc7a200tsbg484-1


write_checkpoint -force -noxdef NexysVideo_A.dcp

catch { report_utilization -file NexysVideo_A_utilization_synth.rpt -pb NexysVideo_A_utilization_synth.pb }
