webtalk_init -webtalk_dir /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.sim/sim_1/behav/xsim.dir/test_uart_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 14 13:17:34 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f0024d64-f601-4937-b085-9f1e868b0011" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "84eeee341bb54e0f9c96e2254cb4c790" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4960X CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3999.682 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.18_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "135220_KB" -context "xsim\\usage"
webtalk_transmit -clientid 447847052 -regid "" -xml /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.sim/sim_1/behav/xsim.dir/test_uart_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.sim/sim_1/behav/xsim.dir/test_uart_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/d/Dropbox/Xilinx/Projects/nexys_uart/nexys_uart.sim/sim_1/behav/xsim.dir/test_uart_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
